---
- name: apache install and restart
  hosts: prod
  tasks:
    - name: install
      ansible.builtin.dnf:
        name: httpd
        state: present
    - name: start
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
